config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
from django.urls import path

from . import views

app_name = "website"

urlpatterns = [
    path('multi', views.multi_page_view, name='multi'),
    path('amb', views.amb_page_view, name='amb'),
    path('dif', views.dif_page_view, name='dif'),
    path('form', views.form_page_view, name='form'),
    path('tecnicas', views.tecnicas_page_view, name='tecnicas'),
    path('inventario', views.inventario_page_view, name='inventario'),
    path('apresentacao', views.apresentacao_page_view, name='apresentacao'),
    path('intro', views.intro_page_view, name='intro'),
    path('', views.intro_page_view, name='intro'),
    path('contacto', views.contactos_page_view, name='contacto'),
    path('addContacto', views.nova_tarefa_view, name='addContacto'),
    path('editContacto/<int:contacto_id>', views.edita_tarefa_view, name='editContacto'),
    path('apaga/<int:contacto_id>', views.apaga_tarefa_view, name='apaga'),
    path('login/', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
    path('comentarios', views.comentarios_page_view, name="comentarios"),
    path('resultadoComentarios', views.resultadoComentarios_page_view, name="resultadoComentarios"),
    path('resultadoQuizz', views.resultadosQuizz_page_view, name="resultadoQuizz"),
    path('spa', views.spa_page_view, name="spa"),
    path("sections/<int:num>",views.section_page_view, name="section")
]

website/models.py
from django.db import models

# Create your models here.
from django.forms import ModelForm


class Contacto(models.Model):
    email = models.EmailField(max_length=254)
    nome = models.CharField(max_length=30)
    apelido = models.CharField(max_length=30)
    telefone = models.IntegerField(default=911524513)
    dataNascimento = models.DateField(default='2000-12-14')

    def __str__(self):
        return self.nome[:50]


class Comentario(models.Model):
    clareza = models.IntegerField(default=50)
    rigor = models.IntegerField(default=50)
    precisao = models.IntegerField(default=50)
    profundidade = models.IntegerField(default=50)
    amplitude = models.IntegerField(default=50)
    logica = models.IntegerField(default=50)
    significancia = models.IntegerField(default=50)
    originalidade = models.IntegerField(default=50)


class Quizz(models.Model):
    question_CO2 = models.CharField(max_length=30, default=1)
    question_bestseller = models.CharField(max_length=30, default=1)
    question_battery = models.CharField(max_length=30, default=1)
    question_horsepower = models.CharField(max_length=30, default=1)
    question_acce = models.CharField(max_length=30, default=1)
    question_chargers = models.CharField(max_length=30, default=1)
    question_maintenance = models.CharField(max_length=30, default=1)
    question_charging = models.CharField(max_length=30, default=1)
    question_auto = models.CharField(max_length=30, default=1)
    question_eff = models.CharField(max_length=30, default=1)
    contacto = models.ForeignKey(Contacto, on_delete=models.CASCADE, default=1)

class ResultadoQuizz(models.Model):
    resultado = models.IntegerField(default=0)


class Quizzform(ModelForm):
    class Meta:
        model = Quizz
        fields = ['question_CO2', 'question_bestseller', 'question_battery', 'question_horsepower', 'question_acce',
                  'question_chargers', 'question_maintenance', 'question_charging', 'question_auto', 'question_eff']

website/forms.py
from django.forms import ModelForm, ModelChoiceField
from .models import Contacto, Comentario, Quizz, ResultadoQuizz
from django import forms

CO2_Choices = [
    ('combustao', 'Carros a combustao'),
    ('eletricos', 'Carros eletricos'),
]
BestSeller_Choices = [
    ('tesla3', 'Tesla Model 3'),
    ('renaultZoe', 'Renault Zoe'),
    ('nissanL', 'Nissan Leaf'),
]

Battery_Choices = [
    ('tesla3', 'Tesla Model 3'),
    ('hyundaiK', 'Hyundai Kawai'),
    ('nissanL', 'Nissan Leaf'),
]

Horsepower_Choices = [
    ('1kw', '1 KW'),
    ('4kw', '4 KW'),
    ('075kw', '0.75 KW'),
]

Chargers_Choices = [
    ('1200', '1200'),
    ('802', '802'),
    ('1505', '1505'),
]

Charging_Choices = [
    ('20min', '20 minutos'),
    ('30min', '30 minutos'),
    ('60min', '60 minutos')
]

Cars_Choices = [
    ('teslas', 'Tesla Model S'),
    ('teslax', 'Tesla Model X'),
    ('porsche', 'Porsche Taycan'),
]
Cars2_Choices = [
    ('combustao', 'Carros a Combustão'),
    ('eletricos', 'Carros Elétricos'),
    ('hybrid', 'Carros Hibridos'),
    ('hybridPlug', 'Carros Hibridos Plug In'),
]


class ContactoForm(ModelForm):
    class Meta:
        model = Contacto
        fields = '__all__'

        widgets = {
            'id': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '1...'}),
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Jota...'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'JP@sublime.pt...'}),
            'apelido': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Pereira...'}),
            'telefone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '911524513...'}),
            'dataNascimento': forms.DateInput(),
        }


class ComentarioForm(ModelForm):
    class Meta:
        model = Comentario
        fields = '__all__'

        widgets = {
            'clareza': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '1...'}),
            'rigor': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '1...'}),
            'precisao': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '1...'}),
            'profundidade': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '1...'}),
            'amplitude': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '1...'}),
            'logica': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '1...'}),
            'significancia': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '1...'}),
            'originalidade': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '1...'}),
        }


class ResultadoForms(ModelForm):
    class Meta:
        model = ResultadoQuizz
        fields = '__all__'


class QuizzForms(forms.Form):
    question_CO2 = forms.CharField(label='Qual destes carros produz mais C02', widget=forms.Select(choices=CO2_Choices,))
    question_bestseller = forms.CharField(label='Qual o carro elétrico mais vendido',
                                          widget=forms.Select(choices=BestSeller_Choices))
    question_battery = forms.CharField(label='Qual destes carros tem maior autonomia',
                                       widget=forms.Select(choices=Battery_Choices))
    question_horsepower = forms.CharField(label='1 cavalo equivale a quantos KW',
                                          widget=forms.Select(choices=Horsepower_Choices))
    question_acce = forms.CharField(label='Qual é o carro que tem menor emissão de CO2',
                                    widget=forms.Select(choices=CO2_Choices))
    question_chargers = forms.CharField(label='Quantos pontos de carregamento existem em Lisboa? (Junho/2021)',
                                        widget=forms.Select(choices=Chargers_Choices))
    question_maintenance = forms.CharField(label='Qual destes carros necessita de menor manutenção',
                                           widget=forms.Select(choices=CO2_Choices))
    question_charging = forms.CharField(label='Qual o tempo médio de um carregamento ao utilizar um SuperCharger:',
                                        widget=forms.Select(choices=Charging_Choices))
    question_auto = forms.CharField(label='Qual o carro com maior autonomia?',
                                    widget=forms.Select(choices=Cars_Choices))
    question_eff = forms.CharField(label='Qual o tipo de carro com maior eficiência ?',
                                   widget=forms.Select(choices=Cars2_Choices))

website/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
import datetime

from django.urls import reverse

from website.forms import ContactoForm, ComentarioForm, QuizzForms, ResultadoForms
from website.models import Contacto, Comentario, Quizzform, Quizz, ResultadoQuizz
from website.utils import get_plot, media, corrigir, get_plotv2


def home_page_view(request):
    lista = ["HTML", "CSS", "Python", "Django"]
    context = {
        'agora': datetime.datetime.now(),
        'lista': lista,
        'contactos': Contacto.objects.all(),
    }
    return render(request, 'website/base.html', context)


def multi_page_view(request):
    return render(request, 'website/multimedia.html')


def dif_page_view(request):
    return render(request, 'website/diferencas.html')


def amb_page_view(request):
    return render(request, 'website/ambiente.html')


def form_page_view(request):
    fields = ['question_CO2', 'question_bestseller', 'question_battery', 'question_horsepower', 'question_acce',
              'question_chargers', 'question_maintenance', 'question_charging', 'question_auto', 'question_eff']
    answers = []
    b = 0
    if request.method == 'POST':
        form = Quizzform(request.POST)
        if form.is_valid():
            form.save()
            for question in fields:
                answers.append(form.cleaned_data[question])
            request.session['answers'] = answers
            print(answers)
            nota = corrigir(answers)
            b = ResultadoQuizz(resultado=nota)
            b.save()
            notas = ResultadoQuizz.objects.all()
            x = ['Média de todos os Resultados']
            t = [t.resultado for t in notas]
            mediaNotas = media(t)
            chart = get_plotv2(x, mediaNotas)
            context = {'nota': b, 'chart': chart}
            return render(request, 'website/resultadoquizz.html', context)
    form = QuizzForms
    context = {"form": form, 'nota': b}
    return render(request, 'website/form.html', context)


def tecnicas_page_view(request):
    return render(request, 'website/tecnicas.html')


def inventario_page_view(request):
    return render(request, 'website/inventario.html')


def apresentacao_page_view(request):
    return render(request, 'website/video.html')


def intro_page_view(request):
    return render(request, 'website/index.html')


def contactos_page_view(request):
    context = {'contactos': Contacto.objects.all()}
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('website:login'))
    return render(request, 'website/contactos.html', context)


def nova_tarefa_view(request):
    form = ContactoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('website:contacto'))

    context = {'form': form}

    return render(request, 'website/addContacto.html', context)


def edita_tarefa_view(request, contacto_id):
    contacto = Contacto.objects.get(id=contacto_id)
    form = ContactoForm(request.POST or None, instance=contacto)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('website:contacto'))

    context = {'form': form, 'contacto_id': contacto_id}
    return render(request, 'website/editContacto.html', context)


def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(
            request,
            username=username,
            password=password
        )

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('website:contacto'))
        else:
            return render(request, 'website/login.html', {
                'message': 'Credenciais inválidas.'
            })

    return render(request, 'website/login.html')


def logout_view(request):
    logout(request)
    return render(request, 'website/login.html', {
        'message': 'Logged out'})


def apaga_tarefa_view(request, contacto_id):
    Contacto.objects.get(id=contacto_id).delete()
    return HttpResponseRedirect(reverse('website:contacto'))


def resultadoComentarios_page_view(request):
    form = ComentarioForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('website:comentarios'))
    context = {'form': form}
    return render(request, 'website/resultadocomentario.html', context)


def comentarios_page_view(request):
    qs = Comentario.objects.all()
    x = ["Clareza", "Rigor", "Precisao", "Profundidade", "Amplitude", "Logica", "Significancia", "Originalidade"]
    y3 = []
    y = [y.clareza for y in qs]
    y2 = media(y)
    y3.append(y2)
    y = [y.rigor for y in qs]
    y2 = media(y)
    y3.append(y2)
    y = [y.precisao for y in qs]
    y2 = media(y)
    y3.append(y2)
    y = [y.profundidade for y in qs]
    y2 = media(y)
    y3.append(y2)
    y = [y.amplitude for y in qs]
    y2 = media(y)
    y3.append(y2)
    y = [y.logica for y in qs]
    y2 = media(y)
    y3.append(y2)
    y = [y.significancia for y in qs]
    y2 = media(y)
    y3.append(y2)
    y = [y.originalidade for y in qs]
    y2 = media(y)
    y3.append(y2)
    chart = get_plot(x, y3)
    context = {'comentarios': Comentario.objects.all(), 'chart': chart}
    return render(request, 'website/comentario.html', context)


def resultadosQuizz_page_view(request):
    context = []
    return render(request, 'website/resultadoquizz.html', context)


def spa_page_view(request):
    return render(request, 'website/spa.html')


texts = ["O primeiro automóvel com motor de combustão foi criado em 1886 graças ao Engenheiro Mecânico Karl Benz.  "
         "Esse automóvel tinha uma potência de 0,75 cavalos e atingia uma velocidade máxima de 16 km/h",
         "Em 1913, com a execução da primeira linha de montagem por Henry Ford, o custo dos automóveis foi baixando o "
         "que permitiu a adopção deste meio de transporte por parte das massas",
         "Com a crescente preocupação da pegada ambiental, a tendência é adotar soluções 100% elétricas ","Website sobre os Automóveis Elétricos"]


def section_page_view(request, num):
    if 1 <= num <= 4:
        return HttpResponse(texts[num - 1])
    else:
        raise Http404("No Such section")

website/templates/website/addContacto.html
{% extends 'website/base.html' %}

{% block main %}
<h3>Novo contacto</h3>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'website:contacto' %}" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
    </form>
{% endblock %}

website/templates/website/ambiente.html
{% extends 'website/base.html' %}

{% block main %}
        <style>
        body{
            background-color: #5CDB95;
        }
    </style>
    <script>
    function changeColor(){
        document.getElementById("asidetext").style.color = "purple";
        document.getElementById("asidetext1").style.color = "purple";
        document.getElementById("ambtext").style.color = "purple";
        document.getElementById("ambtitulo").style.color = "purple";
    }
    </script>
        <figure class="ambimg">
            {% load static %}
            <img src="{% static 'website/images/ambiente.jpg' %}" width = "300" alt="">
            <figcaption id="ambtitulo">Rede de carregadores da Tesla</figcaption>
        </figure>
        <p id="ambtext" class="ambtext">Com a crescente preocupação com o meio ambiente, a população entendeu que os veículos elétricos seriam uma forma inteligente de ajudar o meio ambiente e continuar a utilizar de maneira igual os meios de transporte. Assim, a primeira vantagem é a diminuição das emissões de dióxido de carbono que estão associadas às alterações climáticas e ao efeito estufa.
        Outra vantagem está relacionado com as energias renováveis, uma vez que podemos considerar estes veículos como “conversores de energias renováveis” já que utilizam estas para conseguir funcionar. Em Portugal a componente de energia renovável é superior à não renovável na rede elétrica, o que facilita uma maior adesão ao uso de energias renováveis. 
        </p>
    <div class="asid">
        <aside>
            <figure>
                {% load static %}
                <img src="{% static 'website/images/audi_etron.jpg' %}" alt="Foto">
            </figure>
        </aside>
        <aside>
            <p id="asidetext">Quando uma bateria deixa de servir para um automóvel ainda tem muitos anos de vida pela frente.</p>
            <p id="asidetext1">É uma forma barata de armazenar energia, com uma esperança de vida na casa dos 20 anos.</p>
        </aside>
        <button type="button" onclick="changeColor()">Mudar Cor do Texto</button>
    </div>

{% endblock %}

website/templates/website/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'website/css/base.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta charset="UTF-8">
    <meta name="author" content="Afonso Colaço & Muhammad Iquibal">
    <meta name="keywords" content="HTML.CSS,Carros Elétricos">
    <meta name="description" content="Website sobre Carros Elétricos">
    <meta name="viewport" content="width = device-width, initial-scale = 1.0">
    <title>Carros Elétricos</title>

    <link rel="shortcut icon" type="image/x-icon" href = "{% static 'website/images/favicon.ico' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    {%  block styles %}
    {% endblock %}
</head>

        <style>
        body{
            background-color: #5CDB95;
        }
    </style>
<body>
     <header class="jumbotron text-center" style="background: #5CDB95">
        <h1 style="font-size: 40px"> Carros Elétricos </h1>
         <nav>
             <a href="{% url 'website:intro' %}" class="btn btn-info">Introdução</a>
             <a href="{% url 'website:multi' %}" class="btn btn-info">Multimédia</a>
             <a href="{% url 'website:dif' %}" class="btn btn-info">Diferenças</a>
             <a href="{% url 'website:amb' %}" class="btn btn-info">Ambiente</a>
             <a href="{% url 'website:form' %}" class="btn btn-info">Form</a>
             <a href="{% url 'website:tecnicas' %}" class="btn btn-info">Técnicas Utilizadas</a>
             <a href="{% url 'website:inventario' %}" class="btn btn-info">Inventário</a>
             <a href="{% url 'website:apresentacao' %}" class="btn btn-info">Apresentação</a>
             <a href="{% url 'website:contacto'%}" class="btn btn-info">Contactos</a>
             <a href="{% url 'website:resultadoComentarios'%}" class="btn btn-info">Comentários</a>
             <a href="{% url 'website:spa'%}" class="btn btn-info">SPA</a>
         </nav>
     </header>
        <main>

            {% block main %}
	        {% endblock main %}

        </main>
        <aside class="col-sm-6">
        </aside>
<footer> </footer>
</body>
</html>

website/templates/website/contactos.html
{% extends 'website/base.html' %}
{% block main %}
    <style>
    main{
        text-align: center;
        align-items: center;
        font-size: 25px;
    }
    </style>
        {% for contacto in contactos %}
           ID: {{ contacto.id}}<br>
           Nome: {{ contacto.nome}}<br>
        <a href="{% url 'website:editContacto' contacto.id %}" class="btn btn-warning  btn-sm" style="float: right; margin-right: 10px ">Editar</a>
        {% endfor %}
    <a href="{% url 'website:addContacto' %}" class="btn btn-success btn-block"> Novo Contacto</a>
    <a href="{% url 'website:logout' %}">Logout</a>
{% endblock %}

website/templates/website/editContacto.html
{% extends 'website/base.html' %}
{% block main %}
<h3>Contacto</h3>
    <form action="{% url 'website:editContacto' contacto_id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'website:contacto' %}" role="button" class="btn btn-warning">Cancelar</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
        <a href="{% url 'website:apaga' contacto_id %}" role="button" class="btn btn-danger">Apagar</a>
    </form>
{% endblock %}

website/templates/website/form.html
{% extends 'website/base.html' %}

{% block main %}
    <style>
      *{
          color:#cc0000;
          font-weight: bold;
      }
      .texto{
          color: white;
      }
      h3{
          color: white;
      }
      h1{
          color: white;
      }

    </style>
    {% load static %}
    <body class="bg" style="background-image: url('{% static "website/images/backform.jpg" %}')">
        <section class="texto">
            <h3>Quizz</h3>
            Nesta parte temos um quizz, onde devem responder às questões propostas.
        </section>
        <br>
        <form method="POST" class="formula" action="{% url 'website:form' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Enviar" class="btn btn-success" >
            </form>
    </body>
{% endblock %}

website/templates/website/index.html
{% extends 'website/base.html' %}

{% block main %}
        <style>
        body{
            background-color: #5CDB95;
        }
    </style>
    <script>
    function rodar(){
        document.querySelector("#audiE").style.transform= "rotate(180deg)";
    }
    </script>
<body>
    <figure>
        {% load static %}
        <img src="{% static 'website/images/tesla.png' %}" alt="Tesla" id="mexe" width="400px">
        <figcaption style="display: none;"><a href="https://www.cleanpng.com/png-tesla-model-s-tesla-model-3-tesla-model-x-tesla-mo-5807824/">Tesla Cartoon</a></figcaption>
    </figure>
    <br>
    <p class="indtext">Bem vindo ao website onde irá adquirir alguns conhecimentos sobre veículos elétricos. <br>
        Neste website poderá:</p>
        <ul>
            <li>Ver conteúdos (imagens e vídeos) sobre alguns carros elétricos</li>
            <li>Ver as diferenças entre carros elétricos e a combustão</li>
            <li>Ver as vantagens para o meio ambiental</li>
            <li>Preencher um pequeno formulário.</li>
        </ul>
       <p class="indtext">A venda de carros elétricos já possui 11% das vendas totais de carros e apesar de Portugal possuir a 5º maior percentagem da Europa, continua a existir várias dúvidas sobre as suas vantagens, desvantagens e diferenças e se são de confiança, por isso esperamos que estes conteúdos esclareçam as suas dúvidas. </p>

       <section>
        <svg width = "242" height = "232">
            {% load static %}
            <image width = "300" height = "225" href = "{% static 'website/images/wordcloud.jpg' %}"></image>
        <a href="{% url 'website:multi' %}">
            <polygon opacity = 0.3 points = "115,1,178,1,178,18,115,16"></polygon>
        </a>
        <a href="{% url 'website:amb' %}">
            <polygon opacity = 0.3 points = "131,163,145,187,204,146,186,124"></polygon>
        </a>
        <a href="{% url 'website:dif' %}">
            <polygon opacity = 0.3 points = "155,55,203,54,202,102,157,101"></polygon>
        </a>
        <a href="{% url 'website:intro' %}">
            <polygon opacity = 0 points = "1,5,100,5,98,224,-1,222"></polygon>
        </a>
        </svg>
    </section>

<div class="asid">
    <aside>
        <figure>
            {% load static %}
            <img id="audiE" src="{% static 'website/images/audi_etron.jpg' %}" alt="Foto" onmouseover="rodar(this)">
        </figure>
    </aside>
    <aside>
        <p>Quando uma bateria deixa de servir para um automóvel ainda tem muitos anos de vida pela frente.</p>
        <p>É uma forma barata de armazenar energia, com uma esperança de vida na casa dos 20 anos.</p>
    </aside>
</div>
{% endblock %}

website/templates/website/inventario.html
{% extends 'website/base.html' %}

{% block main %}
        <style>
        body{
            background-color: #5CDB95;
        }
    </style>
    <table border="1" cellpadding = "10% " cellspacing = 1 bgcolor = "lightblue" align="center">
        <figcaption>Informações sobre o Website</figcaption>
        <thead>
            <tr style="background-color: lightblue;">
                <th>Elementos</th>
                <th>Quantidade</th>
            </tr>
            <tr>
                <td> Páginas </td>
                <td>16 &#128561</td>
            </tr>
            <tr>
                <td> Imagens </td>
                <td>17 &#129409</td>
            </tr>
            <tr>
                <td> Links Externos </td>
                <td>2 &#128279</td>
            </tr>
            <tr>
                <td>Vídeos</td>
                <td>2 &#128249</td>
            </tr> 
            <tr>
                <td>Animações</td>
                <td>6 &#9889</td>
            </tr>
            <tfoot>
            <tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</body>
{% endblock %}

website/templates/website/login.html
{%  extends 'website/base.html' %}


{% block main %}
    <h1>Login</h1>
    {% if message %}
        <div> {{ message }} </div>
    {% endif %}
    <form action="{% url 'website:login' %}" method="POST">
        {% csrf_token %}

        <input type="text" name="username" placeholder="username"><br>
        <input type="password" name="password" placeholder="password"><br>
        <input type="submit" value="Login">
    </form>

{% endblock %}

website/templates/website/resultadocomentario.html
{% extends 'website/base.html' %}
{% block main %}
     <form method="POST" action= "{% url 'website:resultadoComentarios' %}">
        {% csrf_token %}
        {{ form.as_p }}
     <input type="submit" value="Gravar" class="btn btn-success" >
    </form>
{% endblock %}

website/templates/website/resultadoquizz.html
{% extends 'website/base.html' %}

{% block main %}
    {% load static %}
           O Resultado do Quizz é {{ nota.resultado }}/100
    <img src="data:image/png;base64, {{ chart|safe }}">
    {% endblock %}

website/templates/website/spa.html
{% extends 'website/base.html' %}
{% load static %}

{% block main %}
    <style>
        body{
            background-color: #5CDB95;
        }
        button{
            font-size: 18px;
        }
    </style>
    <script>
    function showSection(section) {
        fetch(`/sections/${section}`)
            .then(response => response.text())
            .then(text => {
            document.querySelector('#content').innerHTML = text;
        if (text.includes("Karl")) {
            document.querySelector('#image').src = "{% static "website/images/benz.jpg" %}"
        }
        if (text.includes("Ford")) {
            document.querySelector('#image').src = "{% static "website/images/ford.jpg" %}"
        }
        if (text.includes("elétricas")) {
            document.querySelector('#image').src = "{% static "website/images/audietron.jpg" %}"
        }
        if (text.includes("Website")) {
            document.querySelector('#image').src = "{% static "website/images/pain.jpg" %}"
        }
            });
    }
    document.addEventListener('DOMContentLoaded', function () {
            document.querySelectorAll('button').forEach(button => {
                button.onclick = function () {
                    showSection(this.dataset.section);
                }
            });
        });


    </script>
    <body>
    <button data-section="1">Inicio dos Automóveis</button>
    <button data-section="2">Evolução</button>
    <button data-section="3">Atualidade</button>
    <button data-section="4">Diretório de projetos</button>
    <div id="content"></div>
    <img id="image">
    </body>
{% endblock %}